title: Cube2D Framework
description: Cube2D Framework, A minimal 2D simple and easy to use game development framework written in C++11 that makes [raylib] even easier to use.
theme: just-the-docs

url: https://mastercuber55.github.io/Cube2D-Framework

callouts:
  note:
    title: Note
    color: blue

aux_links:
  "Cube2D Framework on GitHub":
    - "https://github.com/mastercuber55/Cube2D-Framework"

aux_links_new_tab: false

footer_content: "Made With Love By Cube Nerd | Copyright &copy; 2023-2023 Cube Nerd. Distributed by an <a href=\"https://github.com/mastercuber55/Cube2D-Framework/blob/main/LICENSE.txt\">MIT license.</a>"